  services:
  postgres:
    image: postgres:14
    container_name: jobtracker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobtracker-network

volumes:
  postgres_data:

networks:
  jobtracker-network:
